baseURL = 'https://alternate-media.github.io/ai-laptop-reviewer/'
languageCode = 'en-us'
title = 'Laptop Verdict'
canonifyURLs = false
relativeURLs = false

[module]

[[module.mounts]]
source = 'assets'
target = 'assets'
