baseURL = 'https://alternate-media.github.io/ai-laptop-reviewer/'
languageCode = 'en-us'
title = 'Laptop Verdict'
canonifyURLs = true
relativeURLs = true

[module]

[[module.mounts]]
source = 'assets'
target = 'assets'
