baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Laptop Reviews - The Anti-Hype Truth'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'node_modules/bootstrap/scss'
    target = 'assets/scss/bootstrap'